language: ruby
rvm:
 - 2.3.1
services:
  - docker

sudo: required
dist: trusty

env:
  global:
    - DOCKER_IMAGE="jamesabrown/gatekeeper"
    - DOCKER_TAG=$TRAVIS_JOB_ID

script:
 - bundle exec rake test

deploy:
  provider: script
  script: bin/travis_deploy.sh
  on:
    all_branches: true
